### ISSUE TITLE
Rust idioms

### ISSUE THREAD

**Issue by theotherphil** [GPSnoopy/RayTracingInOneWeekend#1]
Some unsolicited drive-by comments.

`cargo clippy` is often helpful for spotting things that could be done slightly more idiomatically. (It has some lints you'll no doubt want to ignore, but has a couple of useful results for your current Rust branch.)

You could use macros to make defining the `Vec3` operations less verbose.

`Option`'s `map_or` and `map_or_else` methods make code like this slightly neater (or at least more idiomatic. YMMV): https://github.com/GPSnoopy/RayTracingInOneWeekend/blob/rust_impl/rust/src/main.rs#L156, https://github.com/GPSnoopy/RayTracingInOneWeekend/blob/rust_impl/rust/src/dielectric.rs#L26

**Comment by GPSnoopy** [comment]
Thanks for the tips!

I've applied most of your suggestions. I'll the macros out for the moment, until the overall complexity justifies them.
